// GENERATED by `pnpm vendor:engine` from packages/engine/src — do not edit.
/**
 * Domain types shared across the engine. These mirror the Postgres enums in
 * `packages/db` — keep the two in sync (see docs/SPEC.md §6).
 */

export type Handedness = 'R' | 'L';

export type ClubKind = 'driver' | 'wood' | 'hybrid' | 'iron' | 'wedge' | 'putter';

export type Lie =
  | 'tee'
  | 'fairway'
  | 'first_cut'
  | 'rough'
  | 'deep_rough'
  | 'sand'
  | 'hardpan'
  | 'pine_straw'
  | 'green';

export type SlopeStrength = 'none' | 'mild' | 'severe';

export interface StanceSlope {
  uphill: SlopeStrength;
  downhill: SlopeStrength;
  ballAboveFeet: SlopeStrength;
  ballBelowFeet: SlopeStrength;
}

export const FLAT_STANCE: StanceSlope = {
  uphill: 'none',
  downhill: 'none',
  ballAboveFeet: 'none',
  ballBelowFeet: 'none',
};

export type Strike = 'good' | 'fat' | 'thin' | 'toe' | 'heel' | 'top' | 'shank';

export type Shape = 'straight' | 'draw' | 'fade';

export type ShotSource = 'course' | 'sim' | 'manual';

export type Penalty = 'none' | 'lateral' | 'yellow' | 'ob' | 'unplayable';

/** Feature kinds a course polygon can carry (docs/SPEC.md §6.2). */
export type FeatureKind =
  | 'fairway'
  | 'first_cut'
  | 'rough'
  | 'deep_rough'
  | 'bunker'
  | 'water'
  | 'ob'
  | 'hardpan'
  | 'pine_straw'
  | 'tree'
  | 'wooded'
  | 'cart_path';

/** Weather + terrain snapshot taken at the moment of a shot (SI units). */
export interface Conditions {
  /** Wind speed at 10 m, m/s. */
  windSpeedMps: number;
  /** Meteorological direction the wind blows FROM, degrees true. */
  windFromDeg: number;
  gustMps?: number;
  tempC: number;
  pressureHpa: number;
  elevationStartM: number;
  /** Elevation at the target (before the shot) or at the finish (after). */
  elevationEndM: number;
  /** True when the player overrode the API wind. */
  override?: boolean;
}

export const STANDARD_CONDITIONS: Conditions = {
  windSpeedMps: 0,
  windFromDeg: 0,
  tempC: 20,
  pressureHpa: 1013.25,
  elevationStartM: 0,
  elevationEndM: 0,
};

/**
 * A shot result expressed in the club frame: +along is down the intended
 * line, +lateral is to the player's right (regardless of handedness).
 */
export interface FrameResult {
  alongM: number;
  lateralM: number;
}
