// GENERATED by `pnpm vendor:engine` from packages/engine/src — do not edit.
/**
 * Learned condition coefficients (docs/SPEC.md §8.6, decision 007).
 *
 * For each club kind with ≥ 60 usable course shots, `k_head`, `k_tail`,
 * `k_cross(kind)` and `k_elev(kind)` are re-estimated from the player's own
 * residuals. With μ the club's current neutral pattern mean and the
 * prediction made with the default coefficients (all other terms — lie,
 * slope, density, hang — from `opts.model`):
 *
 *   r_along   = observed.along − predicted(μ).along
 *             = c_a·A + δ_head·(−A·W_h⁺) + δ_tail·(A·W_t⁺) + δ_elev·(−Δh) + ε
 *   r_lateral = observed.lateral − predicted(μ).lateral
 *             = c_l·μ_along + δ_cross·(μ_along · W_c · hang) + ε
 *
 * where A = μ_along · lie factor · (1 + slope), W_h⁺ / W_t⁺ the head / tail
 * components and δ = k − k_default. The δ terms are exact partial
 * derivatives of the linear model (decision 002), so the regression is
 * linear in δ. c_a / c_l are free intercepts (a fractional bias of the
 * baseline): μ was itself normalised with the previous coefficients, and
 * without them its bias would leak into k_head / k_tail.
 *
 * The δ are fitted by weighted ridge regression (recency weights, §8.2)
 * towards 0 (= the defaults) with λ_j = N₀ · D̃_jj / n_j: D̃_jj is the
 * information about coefficient j once the intercept is profiled out and
 * n_j the recency-weighted number of shots with a non-zero component, so
 * the prior counts as N₀ = 60 average informing shots and, for a
 * coefficient not confounded with the others, keeps weight N₀ / (N₀ + n_j)
 * — one half at 60 shots. Every coefficient is finally clamped to
 * [0.3×, 3×] its default so a bad batch cannot flip a sign or explode.
 */
import type {
  ClubKind,
  Conditions,
  FrameResult,
  Handedness,
  Lie,
  StanceSlope,
} from '../types/index.ts';
import { FLAT_STANCE, STANDARD_CONDITIONS } from '../types/index.ts';
import type { PatternShot } from '../dispersion/types.ts';
import {
  DEFAULT_HALF_LIFE_DAYS,
  isExcludedShot,
  shotWeight,
  toEpochMs,
} from '../dispersion/weights.ts';
import { applyConditions, windComponents, type ConditionContext } from './index.ts';
import {
  DEFAULT_CONDITION_MODEL,
  type ConditionModelOverrides,
  type ConditionModelV1,
} from './model.ts';

/** Minimum usable course shots per club kind before anything is learned (§8.6). */
export const LEARN_MIN_SHOTS = 60;

/** Prior strength N₀: the defaults count as this many of the player's shots. */
export const LEARN_PRIOR_SHOTS = 60;

/** Learned coefficients are clamped to [min, max] × their default. */
export const LEARN_CLAMP = { min: 0.3, max: 3 } as const;

/**
 * Snapshots with more wind than this (≈ 45 mph) are left out: they are more
 * likely bad data than golf, and keep the air multiplier far from its floor
 * so the model stays linear in the coefficients.
 */
export const LEARN_MAX_WIND_MPS = 20;

/** Club kinds whose coefficients can be learned (putts have their own model). */
export const LEARNABLE_KINDS: readonly ClubKind[] = ['driver', 'wood', 'hybrid', 'iron', 'wedge'];

/**
 * One course shot for the fit: the observed club-frame result, everything
 * the condition model needs, and the club's current neutral pattern mean.
 * The {@link PatternShot} fields drive the §8.1 exclusions and recency weight.
 */
export interface LearnShot extends Omit<PatternShot, 'alongM' | 'lateralM' | 'bucketKey'> {
  observed: FrameResult;
  /** Current neutral pattern mean of the shot's club (`club_patterns`). */
  neutralMean: FrameResult;
  club: { kind: ClubKind; loftDeg?: number };
  lineBearingDeg: number;
  conditions: Conditions;
  lie: Lie;
  slope: StanceSlope;
  handedness: Handedness;
}

export interface LearnOptions {
  /** Recency reference. Default: the latest `playedAt` among usable shots. */
  now?: Date | number;
  /** Recency half-life, days (§8.2). Default 180. */
  halfLifeDays?: number;
  /**
   * Model supplying the terms that are not learned (lie, slope, density,
   * hang). Its wind/elevation coefficients are ignored: the prediction and
   * the prior always use {@link DEFAULT_CONDITION_MODEL}'s.
   */
  model?: ConditionModelV1;
  /** Default {@link LEARN_MIN_SHOTS}. */
  minShots?: number;
  /** Default {@link LEARN_PRIOR_SHOTS}; must be > 0. */
  priorShots?: number;
}

export interface CoefficientEstimate {
  /** Posterior value, clamped (the default when not fitted). */
  value: number;
  /** The default it was shrunk towards. */
  prior: number;
  /** Posterior standard error; null when not fitted or no shot informs it. */
  se: number | null;
  /** Recency-weighted count of shots with a non-zero component for it. */
  n: number;
  /** True when the clamp moved the value. */
  clamped: boolean;
}

export interface KindConditionEstimate {
  kind: ClubKind;
  /** Usable shots of this kind. */
  n: number;
  /** Σ recency weights of those shots. */
  nEffective: number;
  /** False below the minimum: every value is then the default, untouched. */
  fitted: boolean;
  kHead: CoefficientEstimate;
  kTail: CoefficientEstimate;
  kCross: CoefficientEstimate;
  kElev: CoefficientEstimate;
}

interface Row {
  w: number;
  /** Along features: intercept (A), head, tail, elevation. */
  xa: [number, number, number, number];
  ra: number;
  /** Lateral features: intercept (μ_along), crosswind drift. */
  xl: [number, number];
  rl: number;
}

const priorsFor = (kind: ClubKind) => ({
  kHead: DEFAULT_CONDITION_MODEL.wind.headPerMps,
  kTail: DEFAULT_CONDITION_MODEL.wind.tailPerMps,
  kCross: DEFAULT_CONDITION_MODEL.wind.crossPerMps[kind],
  kElev: DEFAULT_CONDITION_MODEL.elevation.perMetre[kind],
});

/** `model` with the learnable coefficients reset to the defaults. */
function withDefaultCoefficients(model: ConditionModelV1): ConditionModelV1 {
  const d = DEFAULT_CONDITION_MODEL;
  return {
    ...model,
    wind: {
      ...model.wind,
      headPerMps: d.wind.headPerMps,
      tailPerMps: d.wind.tailPerMps,
      crossPerMps: d.wind.crossPerMps,
    },
    elevation: d.elevation,
  };
}

const asPatternShot = (s: LearnShot): PatternShot => ({
  ...s,
  alongM: s.observed.alongM,
  lateralM: s.observed.lateralM,
});

function isLearnable(s: LearnShot): boolean {
  if (s.source !== 'course' || s.strike !== 'good') return false;
  if (s.club.kind === 'putter' || s.lie === 'green') return false;
  if (isExcludedShot(asPatternShot(s))) return false;
  if (!(s.neutralMean.alongM > 0) || !Number.isFinite(s.neutralMean.lateralM)) return false;
  return s.conditions.windSpeedMps <= LEARN_MAX_WIND_MPS;
}

/** Features and residuals of one shot, or null if any is non-finite. */
function rowFor(s: LearnShot, w: number, predModel: ConditionModelV1): Row | null {
  const ctx: ConditionContext = {
    club: s.club,
    lineBearingDeg: s.lineBearingDeg,
    conditions: s.conditions,
    lie: s.lie,
    slope: s.slope,
    handedness: s.handedness,
    model: predModel,
  };
  const mu = s.neutralMean;
  const predicted = applyConditions(mu, ctx);
  // A = μ · lie · (1 + slope): the along result in calm, standard, level air.
  const a = applyConditions(mu, { ...ctx, conditions: STANDARD_CONDITIONS }).alongM;
  // μ_along · W_c · hang: the drift a unit k_cross would give, slope removed.
  const unitCross: ConditionModelV1 = {
    ...predModel,
    wind: {
      ...predModel.wind,
      crossPerMps: { driver: 1, wood: 1, hybrid: 1, iron: 1, wedge: 1, putter: 1 },
    },
  };
  const drift = applyConditions(
    { alongM: mu.alongM, lateralM: 0 },
    { ...ctx, slope: FLAT_STANCE, model: unitCross },
  ).lateralM;
  const { headMps } = windComponents(
    s.conditions.windSpeedMps,
    s.conditions.windFromDeg,
    s.lineBearingDeg,
  );
  const row: Row = {
    w,
    xa: [
      a,
      -a * Math.max(headMps, 0),
      a * Math.max(-headMps, 0),
      -(s.conditions.elevationEndM - s.conditions.elevationStartM),
    ],
    ra: s.observed.alongM - predicted.alongM,
    xl: [mu.alongM, drift],
    rl: s.observed.lateralM - predicted.lateralM,
  };
  const all = [...row.xa, row.ra, ...row.xl, row.rl];
  return all.every(Number.isFinite) ? row : null;
}

/** Lower-triangular Cholesky factor of a symmetric positive-definite matrix. */
function cholesky(m: readonly (readonly number[])[]): number[][] {
  const n = m.length;
  const l = m.map(() => new Array<number>(n).fill(0));
  for (let i = 0; i < n; i++) {
    for (let j = 0; j <= i; j++) {
      let s = m[i]![j]!;
      for (let k = 0; k < j; k++) s -= l[i]![k]! * l[j]![k]!;
      l[i]![j] = i === j ? Math.sqrt(s) : s / l[j]![j]!;
    }
  }
  return l;
}

/** Solve (L Lᵀ) x = b. */
function cholSolve(l: readonly (readonly number[])[], b: readonly number[]): number[] {
  const n = b.length;
  const y = new Array<number>(n).fill(0);
  for (let i = 0; i < n; i++) {
    let s = b[i]!;
    for (let k = 0; k < i; k++) s -= l[i]![k]! * y[k]!;
    y[i] = s / l[i]![i]!;
  }
  const x = new Array<number>(n).fill(0);
  for (let i = n - 1; i >= 0; i--) {
    let s = y[i]!;
    for (let k = i + 1; k < n; k++) s -= l[k]![i]! * x[k]!;
    x[i] = s / l[i]![i]!;
  }
  return x;
}

interface RidgeResult {
  delta: number[];
  se: (number | null)[];
  n: number[];
}

/**
 * Weighted ridge regression of y on x. Column 0 is a free (unpenalised)
 * intercept; the other coefficients are shrunk towards δ = 0 with
 * λ_j = n0 · D̃_jj / n_j, where D̃_jj is the information about coefficient j
 * once the intercept is profiled out (a Schur complement) and n_j the
 * weighted count of shots with x_j ≠ 0. A coefficient with no information
 * of its own (an all-zero column, or one proportional to the intercept) is
 * pinned to δ ≈ 0 with a large λ and reported with n = 0 and no SE.
 * Posterior covariance σ̂² (XᵀWX + Λ)⁻¹, σ̂² from the weighted residuals.
 * Results are for columns 1…p−1.
 */
function ridge(
  points: readonly { w: number; x: readonly number[]; y: number }[],
  n0: number,
): RidgeResult {
  const p = points[0]!.x.length;
  const d = Array.from({ length: p }, () => new Array<number>(p).fill(0));
  const b = new Array<number>(p).fill(0);
  const count = new Array<number>(p).fill(0);
  let wSum = 0;
  for (const { w, x, y } of points) {
    wSum += w;
    for (let i = 0; i < p; i++) {
      if (x[i] !== 0) count[i]! += w;
      b[i]! += w * x[i]! * y;
      for (let j = 0; j < p; j++) d[i]![j]! += w * x[i]! * x[j]!;
    }
  }
  const d00 = d[0]![0]!;
  const informed = d.map((row, j) => {
    const own = row[j]! - (row[0]! * row[0]!) / d00;
    return j > 0 && own > 1e-9 * row[j]! ? own : null;
  });
  const lambda = informed.map((own, j) => {
    if (j === 0) return 0;
    return own !== null ? (n0 * own) / count[j]! : n0 * Math.max(d[j]![j]!, 1);
  });
  const m = d.map((row, i) => row.map((v, j) => (i === j ? v + lambda[i]! : v)));
  const l = cholesky(m);
  const delta = cholSolve(l, b);
  let ss = 0;
  for (const { w, x, y } of points) {
    const e = y - x.reduce((s, xi, i) => s + xi * delta[i]!, 0);
    ss += w * e * e;
  }
  const sigma2 = ss / Math.max(wSum - p, 1);
  const se = informed.map((own, i) => {
    if (own === null) return null;
    const unit = new Array<number>(p).fill(0);
    unit[i] = 1;
    return Math.sqrt(sigma2 * cholSolve(l, unit)[i]!);
  });
  const n = informed.map((own, i) => (own === null ? 0 : count[i]!));
  return { delta: delta.slice(1), se: se.slice(1), n: n.slice(1) };
}

function estimate(prior: number, delta: number, se: number | null, n: number): CoefficientEstimate {
  const raw = prior + delta;
  const value = Math.min(prior * LEARN_CLAMP.max, Math.max(prior * LEARN_CLAMP.min, raw));
  return { value, prior, se, n, clamped: value !== raw };
}

const unfitted = (prior: number): CoefficientEstimate => ({
  value: prior,
  prior,
  se: null,
  n: 0,
  clamped: false,
});

/**
 * Fit `k_head`, `k_tail`, `k_cross`, `k_elev` per club kind (§8.6; see the
 * module comment). Returns one entry per learnable kind that has at least one
 * usable shot, in {@link LEARNABLE_KINDS} order; kinds below `minShots` come
 * back `fitted: false` with the defaults untouched. Excluded: non-course,
 * miss-tagged (strike ≠ good), penalty, putt and badly reconstructed shots
 * (§8.1 via `isExcludedShot`), shots without a positive neutral mean, gale
 * snapshots and non-finite inputs.
 */
export function fitConditionCoefficients(
  shots: readonly LearnShot[],
  opts: LearnOptions = {},
): KindConditionEstimate[] {
  const n0 = opts.priorShots ?? LEARN_PRIOR_SHOTS;
  if (!(n0 > 0)) throw new RangeError('priorShots must be > 0');
  const minShots = opts.minShots ?? LEARN_MIN_SHOTS;
  const halfLife = opts.halfLifeDays ?? DEFAULT_HALF_LIFE_DAYS;
  const predModel = withDefaultCoefficients(opts.model ?? DEFAULT_CONDITION_MODEL);

  const usable = shots.filter(isLearnable);
  const now = opts.now ?? usable.reduce((m, s) => Math.max(m, toEpochMs(s.playedAt)), -Infinity);
  const byKind = new Map<ClubKind, Row[]>();
  for (const s of usable) {
    const w = shotWeight(asPatternShot(s), now, halfLife);
    const row = w > 0 ? rowFor(s, w, predModel) : null;
    if (row === null) continue;
    const list = byKind.get(s.club.kind) ?? [];
    list.push(row);
    byKind.set(s.club.kind, list);
  }

  const out: KindConditionEstimate[] = [];
  for (const kind of LEARNABLE_KINDS) {
    const rows = byKind.get(kind);
    if (!rows) continue;
    const prior = priorsFor(kind);
    const nEffective = rows.reduce((s, r) => s + r.w, 0);
    if (rows.length < minShots) {
      out.push({
        kind,
        n: rows.length,
        nEffective,
        fitted: false,
        kHead: unfitted(prior.kHead),
        kTail: unfitted(prior.kTail),
        kCross: unfitted(prior.kCross),
        kElev: unfitted(prior.kElev),
      });
      continue;
    }
    const along = ridge(
      rows.map((r) => ({ w: r.w, x: r.xa, y: r.ra })),
      n0,
    );
    const lateral = ridge(
      rows.map((r) => ({ w: r.w, x: r.xl, y: r.rl })),
      n0,
    );
    out.push({
      kind,
      n: rows.length,
      nEffective,
      fitted: true,
      kHead: estimate(prior.kHead, along.delta[0]!, along.se[0] as number | null, along.n[0]!),
      kTail: estimate(prior.kTail, along.delta[1]!, along.se[1] as number | null, along.n[1]!),
      kElev: estimate(prior.kElev, along.delta[2]!, along.se[2] as number | null, along.n[2]!),
      kCross: estimate(
        prior.kCross,
        lateral.delta[0]!,
        lateral.se[0] as number | null,
        lateral.n[0]!,
      ),
    });
  }
  return out;
}

/** Four significant digits: enough precision, and stable stored JSON. */
const sig4 = (v: number): number => Number(v.toPrecision(4));

/** n-weighted mean of the informed estimates, or null if none is informed. */
function pooled(cs: readonly CoefficientEstimate[]): number | null {
  const informed = cs.filter((c) => c.n > 0);
  if (!informed.length) return null;
  const n = informed.reduce((s, c) => s + c.n, 0);
  return sig4(informed.reduce((s, c) => s + c.n * c.value, 0) / n);
}

/**
 * The `profiles.condition_overrides` fragment for a fit: `k_cross` and
 * `k_elev` for every fitted kind with informing shots, and — because
 * `ConditionModelV1` keeps single head/tail coefficients (decision 002) — the
 * n-weighted mean of the fitted kinds' `k_head` / `k_tail`. Values are
 * rounded to 4 significant digits (still within the clamps). Nothing fitted
 * → `{}`. The version is never part of an override.
 */
export function toConditionOverrides(
  estimates: readonly KindConditionEstimate[],
): ConditionModelOverrides {
  const fitted = estimates.filter((e) => e.fitted);
  const cross: Partial<Record<ClubKind, number>> = {};
  const elev: Partial<Record<ClubKind, number>> = {};
  for (const e of fitted) {
    if (e.kCross.n > 0) cross[e.kind] = sig4(e.kCross.value);
    if (e.kElev.n > 0) elev[e.kind] = sig4(e.kElev.value);
  }
  const wind: NonNullable<ConditionModelOverrides['wind']> = {};
  const head = pooled(fitted.map((e) => e.kHead));
  const tail = pooled(fitted.map((e) => e.kTail));
  if (head !== null) wind.headPerMps = head;
  if (tail !== null) wind.tailPerMps = tail;
  if (Object.keys(cross).length) wind.crossPerMps = cross;
  const out: ConditionModelOverrides = {};
  if (Object.keys(wind).length) out.wind = wind;
  if (Object.keys(elev).length) out.elevation = { perMetre: elev };
  return out;
}
