// GENERATED by `pnpm vendor:engine` from packages/engine/src — do not edit.
/**
 * Decision and execution grading (docs/SPEC.md §9.5).
 *
 * All `E` values are expected strokes remaining AFTER the shot, on the same
 * basis as `E_option` in §9.2 (penalty strokes included, 0 when holed):
 * - `eBest`   — best option the engine found,
 * - `eChosen` — the option on the card at Hit,
 * - `eActual` — where the ball actually finished (+ any penalty),
 * - `eP20`    — the chosen pattern's 20th-percentile outcome, i.e. the value
 *               that 80 % of simulated outcomes beat (lower E is better).
 */
import type { SgCategory } from './strokesGained.ts';

export type Grade = 'good' | 'poor';

/** A decision costing at most this many strokes is still graded good. */
export const DECISION_GOOD_MAX_LOSS = 0.05;

export interface ShotGradeInput {
  eBest: number;
  eChosen: number;
  eActual: number;
  eP20: number;
}

export interface ShotGrade {
  /** `E(chosen) − E(best)`, ≥ 0. */
  strategyLoss: number;
  /**
   * `sg_shot − sg_expected_given_choice` = `E(chosen) − E(actual)`.
   * Negative means worse than the pattern predicted.
   */
  executionLoss: number;
  decisionGrade: Grade;
  executionGrade: Grade;
}

export function gradeShot({ eBest, eChosen, eActual, eP20 }: ShotGradeInput): ShotGrade {
  const strategyLoss = Math.max(0, eChosen - eBest);
  return {
    strategyLoss,
    executionLoss: eChosen - eActual,
    decisionGrade: strategyLoss <= DECISION_GOOD_MAX_LOSS ? 'good' : 'poor',
    executionGrade: eActual > eP20 ? 'poor' : 'good',
  };
}

/** A graded shot plus optional identifiers carried through to the summary. */
export interface GradedShot extends ShotGrade {
  shotId?: string;
  clubId?: string | null;
  category?: SgCategory | null;
}

export interface GradingTotals {
  /** Strokes lost to strategy (≥ 0). */
  strategyLoss: number;
  /** Net execution result; negative = strokes lost to execution. */
  executionLoss: number;
  /** Net strokes lost overall: `strategyLoss − executionLoss`. */
  cost: number;
  count: number;
}

export interface GradeMatrix {
  goodDecisionGoodExecution: number;
  goodDecisionPoorExecution: number;
  poorDecisionGoodExecution: number;
  poorDecisionPoorExecution: number;
}

export interface RoundGradingSummary<T extends GradedShot> {
  totals: GradingTotals;
  byClub: Record<string, GradingTotals>;
  byCategory: Partial<Record<SgCategory, GradingTotals>>;
  matrix: GradeMatrix;
  /** Up to five shots with the highest positive cost, most expensive first. */
  mostExpensive: { shot: T; cost: number }[];
}

/** Net strokes a graded shot cost versus the best option executed as expected. */
export const shotCost = (g: ShotGrade): number => g.strategyLoss - g.executionLoss;

const emptyTotals = (): GradingTotals => ({ strategyLoss: 0, executionLoss: 0, cost: 0, count: 0 });

function add(t: GradingTotals, g: ShotGrade): void {
  t.strategyLoss += g.strategyLoss;
  t.executionLoss += g.executionLoss;
  t.cost += shotCost(g);
  t.count += 1;
}

export function roundGradingSummary<T extends GradedShot>(
  shots: readonly T[],
): RoundGradingSummary<T> {
  const totals = emptyTotals();
  const byClub: Record<string, GradingTotals> = {};
  const byCategory: Partial<Record<SgCategory, GradingTotals>> = {};
  const matrix: GradeMatrix = {
    goodDecisionGoodExecution: 0,
    goodDecisionPoorExecution: 0,
    poorDecisionGoodExecution: 0,
    poorDecisionPoorExecution: 0,
  };
  for (const s of shots) {
    add(totals, s);
    if (s.clubId != null) add((byClub[s.clubId] ??= emptyTotals()), s);
    if (s.category != null) add((byCategory[s.category] ??= emptyTotals()), s);
    const good = s.decisionGrade === 'good';
    if (s.executionGrade === 'good') {
      if (good) matrix.goodDecisionGoodExecution++;
      else matrix.poorDecisionGoodExecution++;
    } else if (good) matrix.goodDecisionPoorExecution++;
    else matrix.poorDecisionPoorExecution++;
  }
  const mostExpensive = shots
    .map((shot) => ({ shot, cost: shotCost(shot) }))
    .filter((x) => x.cost > 0)
    .sort((a, b) => b.cost - a.cost)
    .slice(0, 5);
  return { totals, byClub, byCategory, matrix, mostExpensive };
}
