// GENERATED by `pnpm vendor:engine` from packages/engine/src — do not edit.
/**
 * Evaluate one `(club, aim point)` option (docs/SPEC.md §9.2) by Monte Carlo.
 *
 * Neutral club-frame draws come from `sampleShots` (main + miss mixture), a
 * flyer component stretches a draw by `flyerDistanceFrac` with the lie's
 * flyer probability, the condition model re-applies wind/elevation/density/
 * lie/slope, and the lie's extra σ (§7.4) is added as independent noise.
 * Each landing is classified against the hole and scored with
 * `expectedAfterLanding`.
 *
 * `applyConditions` is affine in the neutral result (see conditions), so it
 * is evaluated twice per option to recover the map and then applied inline;
 * likewise `fromClubFrame` is linear in the frame result. The per-sample loop
 * therefore allocates nothing. Draws depend only on the pattern and seed, so
 * the search reuses them across aim points (common random numbers).
 */
import {
  applyConditions,
  DEFAULT_CONDITION_MODEL,
  predictEffects,
  type ConditionContext,
  type ConditionModelV1,
} from '../conditions/index.ts';
import { ellipsePolygon, mulberry32, sampleShots, type ClubPattern } from '../dispersion/index.ts';
import {
  EARTH_RADIUS_M,
  fromClubFrame,
  haversineDistanceM,
  initialBearingDeg,
  toLocalXY,
  type LatLng,
} from '../geo/index.ts';
import { degToRad, radToDeg } from '../units/index.ts';
import type { BaselineId, BaselineTable } from '../scoring/index.ts';
import type {
  ClubKind,
  Conditions,
  FeatureKind,
  Handedness,
  Lie,
  StanceSlope,
} from '../types/index.ts';
import { expectedAfterLanding, type StartContext } from './expected.ts';
import { classifyLanding, type PreparedHole } from './geometry.ts';

/** Default Monte-Carlo sample count (§9.2). */
export const DEFAULT_SAMPLES = 400;

export interface StrategyClub {
  id: string;
  /** Short display name ("7i"); defaults to `id` in explanations. */
  label?: string;
  kind: ClubKind;
  loftDeg?: number;
  /** Neutral pattern (`club_patterns.params`). */
  pattern: ClubPattern;
}

/** Everything about the position except the club and aim. */
export interface ShotContext {
  start: LatLng;
  startLie: Lie;
  pin: LatLng;
  conditions: Conditions;
  slope: StanceSlope;
  handedness: Handedness;
  hole: PreparedHole;
  baseline: BaselineTable | BaselineId;
  /** Condition-model coefficients; defaults to `DEFAULT_CONDITION_MODEL`. */
  model?: ConditionModelV1;
}

export interface EvaluateOptionInput extends ShotContext {
  club: StrategyClub;
  aim: LatLng;
  /** Default {@link DEFAULT_SAMPLES}. */
  samples?: number;
  seed: number;
}

export interface OptionEvaluation {
  /** Mean expected strokes to hole out after this shot, penalties included. */
  expectedStrokes: number;
  pFairway: number;
  pGreen: number;
  /** Bunkers, penalty areas (by kind), trees and woods. OB is in `pOb` only. */
  pHazardByKind: Partial<Record<FeatureKind, number>>;
  pOb: number;
  /** Any penalty stroke, OB included. */
  pPenalty: number;
  /** Mean distance to the pin the next shot is played from (OB: the start). */
  expectedRemainingM: number;
  /** Conditioned main-pattern 80 % ellipse (§8.7), closed ring. */
  ellipse80: LatLng[];
  /** Mean of the simulated landings. */
  meanLanding: LatLng;
}

/** Pre-drawn neutral samples plus the auxiliary uniforms/normals, reusable across aims. */
export interface ClubDraws {
  n: number;
  along: Float64Array;
  lateral: Float64Array;
  /** Uniform in [0, 1): flyer when below the lie's flyer probability. */
  flyerU: Float64Array;
  /** Standard normals for the lie's extra σ. */
  zAlong: Float64Array;
  zLateral: Float64Array;
}

/** Draw `n` samples for a pattern. Same `(pattern, n, seed)` ⇒ same draws. */
export function drawSamples(pattern: ClubPattern, n: number, seed: number): ClubDraws {
  const shots = sampleShots(pattern, n, seed);
  const count = shots.length;
  const d: ClubDraws = {
    n: count,
    along: new Float64Array(count),
    lateral: new Float64Array(count),
    flyerU: new Float64Array(count),
    zAlong: new Float64Array(count),
    zLateral: new Float64Array(count),
  };
  // An independent stream for the lie components so they don't alias the pattern draws.
  const rand = mulberry32((seed ^ 0x5bd1e995) >>> 0);
  for (let i = 0; i < count; i++) {
    const s = shots[i]!;
    d.along[i] = s.alongM;
    d.lateral[i] = s.lateralM;
    d.flyerU[i] = rand();
    const r = Math.sqrt(-2 * Math.log(1 - rand()));
    const th = 2 * Math.PI * rand();
    d.zAlong[i] = r * Math.cos(th);
    d.zLateral[i] = r * Math.sin(th);
  }
  return d;
}

/** The condition model for this option as an affine map, plus the lie's stochastic terms. */
interface ConditionedMap {
  bearingDeg: number;
  /** along_c = along_n · F + E;  lateral_c = lateral_n + along_n · L. */
  F: number;
  E: number;
  L: number;
  sigmaAlongM: number;
  sigmaLateralM: number;
  flyerP: number;
  flyerMul: number;
}

function conditionContext(input: EvaluateOptionInput, bearingDeg: number): ConditionContext {
  const club: ConditionContext['club'] = { kind: input.club.kind };
  if (input.club.loftDeg !== undefined) club.loftDeg = input.club.loftDeg;
  const ctx: ConditionContext = {
    club,
    lineBearingDeg: bearingDeg,
    conditions: input.conditions,
    lie: input.startLie,
    slope: input.slope,
    handedness: input.handedness,
  };
  if (input.model !== undefined) ctx.model = input.model;
  return ctx;
}

function conditionedMap(input: EvaluateOptionInput): ConditionedMap {
  const bearingDeg = initialBearingDeg(input.start, input.aim);
  const ctx = conditionContext(input, bearingDeg);
  const o = applyConditions({ alongM: 0, lateralM: 0 }, ctx);
  const u = applyConditions({ alongM: 1, lateralM: 0 }, ctx);
  const eff = predictEffects({ ...ctx, nominalDistanceM: input.club.pattern.distance.mean });
  return {
    bearingDeg,
    F: u.alongM - o.alongM,
    E: o.alongM,
    L: u.lateralM - o.lateralM,
    sigmaAlongM: eff.extraSigmaAlongM,
    sigmaLateralM: eff.extraSigmaLateralM,
    flyerP: eff.flyerProbability,
    flyerMul: 1 + (input.model ?? DEFAULT_CONDITION_MODEL).flyerDistanceFrac,
  };
}

/** Club-frame conditioned mean of the main pattern (no flyer, no miss). */
export function conditionedMean(input: EvaluateOptionInput): { alongM: number; lateralM: number } {
  const m = conditionedMap(input);
  const { distance, lateral } = input.club.pattern;
  return { alongM: distance.mean * m.F + m.E, lateralM: lateral.mean + distance.mean * m.L };
}

/** 80 % ellipse of the conditioned main pattern (§8.7), mapped to lat/lng. */
export function conditionedEllipse80(input: EvaluateOptionInput, steps = 32): LatLng[] {
  const m = conditionedMap(input);
  const p = input.club.pattern;
  const conditioned: ClubPattern = {
    ...p,
    distance: {
      ...p.distance,
      mean: p.distance.mean * m.F + m.E,
      sd: Math.hypot(p.distance.sd * m.F, m.sigmaAlongM),
    },
    lateral: {
      ...p.lateral,
      mean: p.lateral.mean + p.distance.mean * m.L,
      sd_left: Math.hypot(p.lateral.sd_left, m.sigmaLateralM),
      sd_right: Math.hypot(p.lateral.sd_right, m.sigmaLateralM),
    },
  };
  return ellipsePolygon(conditioned, 0.8, steps).map((r) =>
    fromClubFrame(input.start, m.bearingDeg, r),
  );
}

/** {@link evaluateOption} with pre-drawn samples and an optional ellipse. */
export function evaluateWithDraws(
  input: EvaluateOptionInput,
  draws: ClubDraws,
  withEllipse = true,
): OptionEvaluation {
  const m = conditionedMap(input);
  const { start, hole, baseline } = input;
  const θ = degToRad(m.bearingDeg);
  const sinθ = Math.sin(θ);
  const cosθ = Math.cos(θ);
  // fromLocalXY, linearised: degrees per metre north / east at the start.
  const latPerM = radToDeg(1 / EARTH_RADIUS_M);
  const lngPerM = latPerM / Math.cos(degToRad(start.lat));
  const pinXY = toLocalXY(start, input.pin);
  const startCtx: StartContext = {
    lie: input.startLie,
    distanceM: haversineDistanceM(start, input.pin),
  };

  const scratch: LatLng = { lat: 0, lng: 0 };
  let sumE = 0;
  let sumRemaining = 0;
  let sumAlong = 0;
  let sumLateral = 0;
  let nFairway = 0;
  let nGreen = 0;
  let nOb = 0;
  let nPenalty = 0;
  const hazards: Partial<Record<FeatureKind, number>> = {};

  const n = draws.n;
  for (let i = 0; i < n; i++) {
    const na = draws.flyerU[i]! < m.flyerP ? draws.along[i]! * m.flyerMul : draws.along[i]!;
    const along = na * m.F + m.E + draws.zAlong[i]! * m.sigmaAlongM;
    const lateral = draws.lateral[i]! + na * m.L + draws.zLateral[i]! * m.sigmaLateralM;
    sumAlong += along;
    sumLateral += lateral;
    const x = along * sinθ + lateral * cosθ;
    const y = along * cosθ - lateral * sinθ;
    scratch.lat = start.lat + y * latPerM;
    scratch.lng = start.lng + x * lngPerM;
    const pinDistM = Math.hypot(x - pinXY.x, y - pinXY.y);

    const landing = classifyLanding(hole, scratch);
    sumE += expectedAfterLanding(landing, pinDistM, baseline, startCtx);
    if (landing.penalty === 'ob') {
      nOb++;
      nPenalty++;
      sumRemaining += startCtx.distanceM;
      continue;
    }
    sumRemaining += pinDistM;
    if (landing.penalty !== 'none') nPenalty++;
    if (landing.hazard !== null) {
      hazards[landing.hazard] = (hazards[landing.hazard] ?? 0) + 1;
    } else if (landing.lie === 'green') nGreen++;
    else if (landing.lie === 'fairway') nFairway++;
  }

  const inv = n > 0 ? 1 / n : 0;
  const pHazardByKind: Partial<Record<FeatureKind, number>> = {};
  for (const [kind, count] of Object.entries(hazards) as [FeatureKind, number][]) {
    pHazardByKind[kind] = count * inv;
  }
  return {
    expectedStrokes: sumE * inv,
    pFairway: nFairway * inv,
    pGreen: nGreen * inv,
    pHazardByKind,
    pOb: nOb * inv,
    pPenalty: nPenalty * inv,
    expectedRemainingM: sumRemaining * inv,
    ellipse80: withEllipse ? conditionedEllipse80(input) : [],
    meanLanding: fromClubFrame(start, m.bearingDeg, {
      alongM: sumAlong * inv,
      lateralM: sumLateral * inv,
    }),
  };
}

/** Evaluate one `(club, aim)` option (§9.2). Deterministic for a seed. */
export function evaluateOption(input: EvaluateOptionInput): OptionEvaluation {
  const draws = drawSamples(input.club.pattern, input.samples ?? DEFAULT_SAMPLES, input.seed);
  return evaluateWithDraws(input, draws);
}
