// GENERATED by `pnpm vendor:engine` from packages/engine/src — do not edit.
/**
 * Hole geometry as the strategy engine sees it (docs/SPEC.md §6.2, §9.2 step 3),
 * independent of the database row shapes. {@link prepareHole} pre-computes a
 * bbox and a hit test per feature, sorted by precedence, so
 * {@link classifyLanding} is a short loop of bbox checks with an occasional
 * point-in-polygon test and no allocation.
 */
import {
  EARTH_RADIUS_M,
  bboxContains,
  bboxOf,
  pointInPolygon,
  type Bbox,
  type LatLng,
  type Polygon,
} from '../geo/index.ts';
import { degToRad, radToDeg } from '../units/index.ts';
import type { FeatureKind, Lie } from '../types/index.ts';

/** `hole_features.penalty` (§6.2). */
export type FeaturePenalty = 'none' | 'lateral' | 'yellow' | 'ob';

/** One `hole_features` row: a polygon, or a point with a radius (trees). */
export interface HoleFeature {
  kind: FeatureKind;
  penalty: FeaturePenalty;
  polygon?: Polygon;
  point?: LatLng;
  /** Radius around `point`, metres. Defaults to {@link DEFAULT_TREE_RADIUS_M}. */
  radiusM?: number;
}

export interface HoleGeometry {
  green: Polygon;
  greenCentre: LatLng;
  pin: LatLng;
  features: readonly HoleFeature[];
  /** Tee → landing zones → green centre. Used for layup and tee-shot aim stations. */
  lineOfPlay?: readonly LatLng[];
}

/** Canopy radius used for a point feature stored without one. */
export const DEFAULT_TREE_RADIUS_M = 3;

/** Where a ball finished, as far as expected strokes are concerned. */
export interface LandingClass {
  /**
   * Lie the next shot is played from. For penalty areas it is the drop lie
   * (`rough`); for OB it is `rough` too but meaningless — the next shot is
   * replayed from the start (see `expectedAfterLanding`).
   */
  lie: Lie;
  penalty: FeaturePenalty;
  /** Trees and woods: the next shot is a recovery shot (SG category `recovery`). */
  recovery: boolean;
  /** Hazard bucket for `pHazardByKind`; null for fairway/rough/green/OB. */
  hazard: FeatureKind | null;
  feature?: HoleFeature;
}

/** One precedence-sorted hit test. */
interface PreparedEntry {
  rank: number;
  bbox: Bbox;
  hit: (p: LatLng) => boolean;
  result: LandingClass;
}

export interface PreparedHole {
  geometry: HoleGeometry;
  /** Sorted by precedence, highest first; the first hit wins. */
  entries: readonly PreparedEntry[];
}

/**
 * Precedence, highest first: OB > penalty areas (water) > bunker > green >
 * trees/woods > deep rough > rough > first cut > fairway > hardpan/pine straw.
 * Cart paths give free relief and are ignored (the surrounding lie applies).
 */
const RANK = {
  ob: 0,
  penalty: 1,
  bunker: 2,
  green: 3,
  trees: 4,
  deep_rough: 5,
  rough: 6,
  first_cut: 7,
  fairway: 8,
  bare: 9,
} as const;

/** Landing outside every feature. */
export const DEFAULT_LANDING: LandingClass = Object.freeze({
  lie: 'rough',
  penalty: 'none',
  recovery: false,
  hazard: null,
});

type Classified = Omit<LandingClass, 'feature'> & { rank: number };

/** How a feature classifies a ball, or null when it never affects the lie. */
function classifyFeature(f: HoleFeature): Classified | null {
  if (f.kind === 'ob' || f.penalty === 'ob') {
    return { rank: RANK.ob, lie: 'rough', penalty: 'ob', recovery: false, hazard: null };
  }
  // Water is always a penalty area under the Rules; unmarked water counts as yellow.
  if (f.penalty !== 'none' || f.kind === 'water') {
    const penalty = f.penalty === 'none' ? 'yellow' : f.penalty;
    return { rank: RANK.penalty, lie: 'rough', penalty, recovery: false, hazard: f.kind };
  }
  const plain = (rank: number, lie: Lie): Classified => ({
    rank,
    lie,
    penalty: 'none',
    recovery: false,
    hazard: null,
  });
  switch (f.kind) {
    case 'bunker':
      return { ...plain(RANK.bunker, 'sand'), hazard: 'bunker' };
    case 'tree':
    case 'wooded':
      return { ...plain(RANK.trees, 'rough'), recovery: true, hazard: f.kind };
    case 'deep_rough':
      return plain(RANK.deep_rough, 'deep_rough');
    case 'rough':
      return plain(RANK.rough, 'rough');
    case 'first_cut':
      return plain(RANK.first_cut, 'first_cut');
    case 'fairway':
      return plain(RANK.fairway, 'fairway');
    case 'hardpan':
    case 'pine_straw':
      return plain(RANK.bare, f.kind);
    case 'cart_path':
      return null;
  }
}

/** Bbox + hit test for a circle, using the equirectangular plane around its centre. */
function circleTest(c: LatLng, radiusM: number): Pick<PreparedEntry, 'bbox' | 'hit'> {
  const mPerDegLat = degToRad(1) * EARTH_RADIUS_M;
  const mPerDegLng = mPerDegLat * Math.cos(degToRad(c.lat));
  const dLat = radToDeg(radiusM / EARTH_RADIUS_M);
  const dLng = dLat * (mPerDegLat / mPerDegLng);
  const r2 = radiusM * radiusM;
  return {
    bbox: {
      minLat: c.lat - dLat,
      maxLat: c.lat + dLat,
      minLng: c.lng - dLng,
      maxLng: c.lng + dLng,
    },
    hit: (p) => {
      const dy = (p.lat - c.lat) * mPerDegLat;
      const dx = (p.lng - c.lng) * mPerDegLng;
      return dx * dx + dy * dy <= r2;
    },
  };
}

function polygonTest(poly: Polygon): Pick<PreparedEntry, 'bbox' | 'hit'> {
  return { bbox: bboxOf(poly.outer), hit: (p) => pointInPolygon(poly, p) };
}

/** Pre-compute bboxes and precedence order for fast classification. */
export function prepareHole(geometry: HoleGeometry): PreparedHole {
  const entries: PreparedEntry[] = [
    {
      ...polygonTest(geometry.green),
      rank: RANK.green,
      result: Object.freeze({ lie: 'green', penalty: 'none', recovery: false, hazard: null }),
    },
  ];
  for (const feature of geometry.features) {
    const c = classifyFeature(feature);
    if (c === null) continue;
    let shape: Pick<PreparedEntry, 'bbox' | 'hit'>;
    if (feature.polygon !== undefined) shape = polygonTest(feature.polygon);
    else if (feature.point !== undefined) {
      shape = circleTest(feature.point, feature.radiusM ?? DEFAULT_TREE_RADIUS_M);
    } else continue;
    const { rank, ...rest } = c;
    entries.push({ ...shape, rank, result: Object.freeze({ ...rest, feature }) });
  }
  // Array.prototype.sort is stable, so equal ranks keep input order.
  entries.sort((a, b) => a.rank - b.rank);
  return { geometry, entries };
}

/** Classify a landing point. Returns shared, frozen objects: do not mutate. */
export function classifyLanding(prepared: PreparedHole, p: LatLng): LandingClass {
  for (const e of prepared.entries) {
    if (bboxContains(e.bbox, p) && e.hit(p)) return e.result;
  }
  return DEFAULT_LANDING;
}
