// GENERATED by `pnpm vendor:engine` from packages/engine/src — do not edit.
/**
 * Option search (docs/SPEC.md §9.3): pick candidate clubs, sweep aim points,
 * rank by expected strokes and compare with the "obvious club at the pin"
 * baseline.
 *
 * - Approach clubs: conditioned mean within 60–110 % of the pin distance;
 *   aims sweep ±44 m across the pin line at 2 m.
 * - Layup / tee clubs (only when no club reaches 90 % of the pin distance):
 *   the patterns are full swings, so each club's aim station is the point on
 *   the line of play at its conditioned mean distance; the same lateral
 *   sweep runs across the line there. Off the tee every non-putter club is
 *   compared (driver vs 5-wood vs hybrid, §9.3); elsewhere only clubs that
 *   finish at least 40 m short of the pin.
 * - Coarse-to-fine: every third lattice offset (6 m), then ±2 m and ±4 m
 *   around the two best coarse offsets. `exhaustive` evaluates every offset.
 *
 * All options of one club share the same draws (common random numbers), so
 * differences between aims are not Monte-Carlo noise.
 */
import { CONDITION_MODEL_VERSION } from '../conditions/index.ts';
import { DISPERSION_ENGINE_VERSION } from '../dispersion/index.ts';
import {
  destinationPoint,
  fromClubFrame,
  fromLocalXY,
  haversineDistanceM,
  initialBearingDeg,
  toClubFrame,
  toLocalXY,
  type LatLng,
} from '../geo/index.ts';
import type { FrameResult } from '../types/index.ts';
import {
  conditionedEllipse80,
  conditionedMean,
  DEFAULT_SAMPLES,
  drawSamples,
  evaluateWithDraws,
  type ClubDraws,
  type EvaluateOptionInput,
  type OptionEvaluation,
  type ShotContext,
  type StrategyClub,
} from './evaluate.ts';

/** Bump when recommendations would change for the same inputs. */
export const STRATEGY_ENGINE_VERSION = 1;

export const APPROACH_MIN_FRAC = 0.6;
export const APPROACH_MAX_FRAC = 1.1;
/** A club "reaches" when its conditioned mean is at least this share of the pin distance. */
export const REACH_FRAC = 0.9;
/** Non-tee layups finish at least this far short of the pin. */
export const LAYUP_SHORT_OF_PIN_M = 40;
export const AIM_STEP_M = 2;
export const AIM_MAX_M = 45;
export const DEFAULT_MAX_OPTIONS = 5;
export const DEFAULT_SEED = 1;

const MAX_K = Math.floor(AIM_MAX_M / AIM_STEP_M);
const COARSE_STRIDE = 3;
const REFINE_SEEDS = 2;
const REFINE_RADIUS = 2;

export type OptionKind = 'approach' | 'layup';

export interface StrategyOption extends OptionEvaluation {
  clubId: string;
  clubLabel: string;
  kind: OptionKind;
  aim: LatLng;
  /**
   * Aim relative to the pin line (start → pin frame): `alongM` is metres past
   * the pin (negative = short), `lateralM` metres right of the line.
   */
  aimOffsetM: FrameResult;
  /** Metres right of the line of play at the aim (approaches: of the pin line). */
  lineOffsetM: number;
}

export interface RecommendInput extends ShotContext {
  clubs: readonly StrategyClub[];
  isTeeShot?: boolean;
  /** Default 400. */
  samples?: number;
  /** Default {@link DEFAULT_SEED}. */
  seed?: number;
  /** Evaluate every aim offset instead of coarse-to-fine. */
  exhaustive?: boolean;
  /** Default {@link DEFAULT_MAX_OPTIONS}. */
  maxOptions?: number;
}

export interface EngineVersions {
  strategy: number;
  conditionModel: number;
  dispersion: number;
}

export interface Recommendation {
  /** Best aim per club (and kind), best first; at most `maxOptions`. */
  options: StrategyOption[];
  /** The obvious club at the pin (or, for layups, the longest club down the line). */
  baseline: StrategyOption;
  /** Filled by the app with whatever is on the card at Hit (§9.4). */
  chosen?: StrategyOption;
  engineVersion: typeof STRATEGY_ENGINE_VERSION;
  engineVersions: EngineVersions;
  /** `baseline.expectedStrokes − options[0].expectedStrokes`, ≥ 0. */
  savedVsBaseline: number;
  inputsHash: string;
}

/** An option as stored in `shots.recommendation` (the ellipse is re-derivable and omitted). */
export type SnapshotOption = Omit<StrategyOption, 'ellipse80'>;

/** Shape of `shots.recommendation` (§6.3). */
export interface RecommendationSnapshot {
  engineVersions: EngineVersions;
  inputsHash: string;
  options: SnapshotOption[];
  baseline: SnapshotOption;
  chosen: SnapshotOption | null;
  savedVsBaseline: number;
}

/**
 * The point on `line` whose straight-line distance from `start` first reaches
 * `distanceM`, walking the polyline from its first vertex. Past the end of
 * the line it continues from `start` towards the last vertex.
 */
export function pointAlongLine(start: LatLng, line: readonly LatLng[], distanceM: number): LatLng {
  let prev = toLocalXY(start, line[0]!);
  let prevD = Math.hypot(prev.x, prev.y);
  for (let i = 1; i < line.length; i++) {
    const cur = toLocalXY(start, line[i]!);
    const curD = Math.hypot(cur.x, cur.y);
    if (prevD < distanceM && curD >= distanceM) {
      // Solve |prev + t·(cur − prev)| = distanceM for the root in [0, 1].
      const dx = cur.x - prev.x;
      const dy = cur.y - prev.y;
      const a = dx * dx + dy * dy;
      const b = prev.x * dx + prev.y * dy;
      const c = prevD * prevD - distanceM * distanceM;
      const t = (-b + Math.sqrt(b * b - a * c)) / a;
      return fromLocalXY(start, { x: prev.x + t * dx, y: prev.y + t * dy });
    }
    prev = cur;
    prevD = curD;
  }
  return destinationPoint(start, initialBearingDeg(start, line[line.length - 1]!), distanceM);
}

/** Line of play for a position: the hole's, or straight at the pin. */
function lineFor(input: ShotContext): readonly LatLng[] {
  const line = input.hole.geometry.lineOfPlay;
  return line !== undefined && line.length >= 2 ? line : [input.start, input.pin];
}

function evalInput(input: RecommendInput, club: StrategyClub, aim: LatLng): EvaluateOptionInput {
  const ei: EvaluateOptionInput = {
    start: input.start,
    startLie: input.startLie,
    pin: input.pin,
    conditions: input.conditions,
    slope: input.slope,
    handedness: input.handedness,
    hole: input.hole,
    baseline: input.baseline,
    club,
    aim,
    seed: input.seed ?? DEFAULT_SEED,
  };
  if (input.model !== undefined) ei.model = input.model;
  return ei;
}

function toStrategyOption(
  input: RecommendInput,
  club: StrategyClub,
  aim: LatLng,
  ev: OptionEvaluation,
): StrategyOption {
  const { start, pin } = input;
  const pinDist = haversineDistanceM(start, pin);
  const inPinFrame = toClubFrame(start, initialBearingDeg(start, pin), aim);
  const aimOffsetM = { alongM: inPinFrame.alongM - pinDist, lateralM: inPinFrame.lateralM };
  const kind: OptionKind = Math.abs(aimOffsetM.alongM) <= 1 ? 'approach' : 'layup';
  let lineOffsetM = aimOffsetM.lateralM;
  if (kind === 'layup') {
    const station = pointAlongLine(start, lineFor(input), haversineDistanceM(start, aim));
    lineOffsetM = toClubFrame(start, initialBearingDeg(start, station), aim).lateralM;
  }
  return {
    ...ev,
    clubId: club.id,
    clubLabel: club.label ?? club.id,
    kind,
    aim,
    aimOffsetM,
    lineOffsetM,
  };
}

/**
 * Evaluate an arbitrary `(club, aim)` — e.g. the player dragged the aim —
 * on the same basis as {@link recommend}, ready to store as `chosen`.
 */
export function evaluateChoice(
  input: RecommendInput,
  club: StrategyClub,
  aim: LatLng,
): StrategyOption {
  const ei = evalInput(input, club, aim);
  const draws = drawSamples(club.pattern, input.samples ?? DEFAULT_SAMPLES, ei.seed);
  return toStrategyOption(input, club, aim, evaluateWithDraws(ei, draws));
}

interface Sweep {
  club: StrategyClub;
  kind: OptionKind;
  /** Conditioned mean distance of the club, metres. */
  meanM: number;
  /** Aim for lattice offset k (lateral = k · AIM_STEP_M). */
  aimAt: (k: number) => LatLng;
  draws: ClubDraws;
  cache: Map<number, OptionEvaluation>;
}

function evalAt(input: RecommendInput, s: Sweep, k: number): OptionEvaluation {
  let ev = s.cache.get(k);
  if (ev === undefined) {
    ev = evaluateWithDraws(evalInput(input, s.club, s.aimAt(k)), s.draws, false);
    s.cache.set(k, ev);
  }
  return ev;
}

/** Run the lateral sweep; returns the best lattice offset. */
function sweep(input: RecommendInput, s: Sweep): number {
  const ks: number[] = [];
  if (input.exhaustive === true) {
    for (let k = -MAX_K; k <= MAX_K; k++) ks.push(k);
  } else {
    for (let k = -MAX_K; k <= MAX_K; k++) if (k % COARSE_STRIDE === 0) ks.push(k);
  }
  for (const k of ks) evalAt(input, s, k);
  if (input.exhaustive !== true) {
    const seeds = [...s.cache.entries()]
      .sort((a, b) => a[1].expectedStrokes - b[1].expectedStrokes)
      .slice(0, REFINE_SEEDS)
      .map(([k]) => k);
    for (const k0 of seeds) {
      const hi = Math.min(MAX_K, k0 + REFINE_RADIUS);
      for (let k = Math.max(-MAX_K, k0 - REFINE_RADIUS); k <= hi; k++) evalAt(input, s, k);
    }
  }
  let bestK = 0;
  let bestE = Infinity;
  for (const [k, ev] of s.cache) {
    if (ev.expectedStrokes < bestE) {
      bestE = ev.expectedStrokes;
      bestK = k;
    }
  }
  return bestK;
}

/** Search clubs × aims for a position (§9.3). */
export function recommend(input: RecommendInput): Recommendation {
  const { start, pin } = input;
  const pinDist = haversineDistanceM(start, pin);
  const pinBearing = initialBearingDeg(start, pin);
  const seed = input.seed ?? DEFAULT_SEED;
  const samples = input.samples ?? DEFAULT_SAMPLES;

  const clubs = input.clubs
    .filter((c) => c.kind !== 'putter')
    .map((club) => ({ club, meanM: conditionedMean(evalInput(input, club, pin)).alongM }));
  if (clubs.length === 0) throw new RangeError('recommend needs at least one non-putter club');

  const reach = Math.max(...clubs.map((c) => c.meanM));
  const reachesGreen = reach >= REACH_FRAC * pinDist;
  const inWindow = (m: number): boolean =>
    m >= APPROACH_MIN_FRAC * pinDist && m <= APPROACH_MAX_FRAC * pinDist;
  const teeLayup = input.isTeeShot === true && !reachesGreen;
  let approach = teeLayup ? [] : clubs.filter((c) => inWindow(c.meanM));
  const layup = reachesGreen
    ? []
    : clubs.filter(
        (c) =>
          !approach.includes(c) &&
          c.meanM > 0 &&
          (teeLayup || c.meanM <= pinDist - LAYUP_SHORT_OF_PIN_M),
      );
  if (approach.length === 0 && layup.length === 0) {
    // Nothing fits the windows: fall back to the club closest to the pin distance.
    const closest = clubs.reduce((a, b) =>
      Math.abs(b.meanM - pinDist) < Math.abs(a.meanM - pinDist) ? b : a,
    );
    approach = [closest];
  }

  const line = lineFor(input);
  const sweeps: Sweep[] = [];
  for (const { club, meanM } of approach) {
    sweeps.push({
      club,
      kind: 'approach',
      meanM,
      aimAt: (k) => fromClubFrame(start, pinBearing, { alongM: pinDist, lateralM: k * AIM_STEP_M }),
      draws: drawSamples(club.pattern, samples, seed),
      cache: new Map(),
    });
  }
  for (const { club, meanM } of layup) {
    const station = pointAlongLine(start, line, meanM);
    const bearing = initialBearingDeg(start, station);
    sweeps.push({
      club,
      kind: 'layup',
      meanM,
      aimAt: (k) => fromClubFrame(start, bearing, { alongM: meanM, lateralM: k * AIM_STEP_M }),
      draws: drawSamples(club.pattern, samples, seed),
      cache: new Map(),
    });
  }

  const finish = (s: Sweep, k: number): StrategyOption => {
    const aim = s.aimAt(k);
    const ev = evalAt(input, s, k);
    const ellipse80 = conditionedEllipse80(evalInput(input, s.club, aim));
    return toStrategyOption(input, s.club, aim, { ...ev, ellipse80 });
  };

  const best = sweeps
    .map((s) => ({ s, k: sweep(input, s) }))
    .sort(
      (a, b) => evalAt(input, a.s, a.k).expectedStrokes - evalAt(input, b.s, b.k).expectedStrokes,
    )
    .slice(0, input.maxOptions ?? DEFAULT_MAX_OPTIONS);
  const options = best.map(({ s, k }) => finish(s, k));

  // Baseline: the approach club closest to the pin distance, at the pin; with
  // no approach club, the longest layup club straight down the line.
  const baselineSweep =
    approach.length > 0
      ? sweeps
          .filter((s) => s.kind === 'approach')
          .reduce((a, b) => (Math.abs(b.meanM - pinDist) < Math.abs(a.meanM - pinDist) ? b : a))
      : sweeps.reduce((a, b) => (b.meanM > a.meanM ? b : a));
  const baseline = finish(baselineSweep, 0);

  return {
    options,
    baseline,
    engineVersion: STRATEGY_ENGINE_VERSION,
    engineVersions: engineVersions(input),
    savedVsBaseline: Math.max(0, baseline.expectedStrokes - options[0]!.expectedStrokes),
    inputsHash: hashInputs(input),
  };
}

function engineVersions(input: ShotContext): EngineVersions {
  return {
    strategy: STRATEGY_ENGINE_VERSION,
    conditionModel: input.model?.version ?? CONDITION_MODEL_VERSION,
    dispersion: DISPERSION_ENGINE_VERSION,
  };
}

function snapshotOption(o: StrategyOption): SnapshotOption {
  const copy: Partial<StrategyOption> = { ...o };
  delete copy.ellipse80;
  return copy as SnapshotOption;
}

/** The `shots.recommendation` payload for a recommendation and the option chosen at Hit. */
export function toRecommendationSnapshot(
  rec: Recommendation,
  chosen: StrategyOption | null = rec.chosen ?? null,
): RecommendationSnapshot {
  return {
    engineVersions: rec.engineVersions,
    inputsHash: rec.inputsHash,
    options: rec.options.map(snapshotOption),
    baseline: snapshotOption(rec.baseline),
    chosen: chosen === null ? null : snapshotOption(chosen),
    savedVsBaseline: rec.savedVsBaseline,
  };
}

/** JSON with object keys sorted, so equal inputs hash equally regardless of key order. */
function stableStringify(v: unknown): string {
  if (Array.isArray(v)) return `[${v.map(stableStringify).join(',')}]`;
  if (typeof v === 'object' && v !== null) {
    const obj = v as Record<string, unknown>;
    const keys = Object.keys(obj).sort();
    return `{${keys.map((k) => `${JSON.stringify(k)}:${stableStringify(obj[k])}`).join(',')}}`;
  }
  return JSON.stringify(v);
}

/** FNV-1a 32-bit, hex. */
function fnv1a(s: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, '0');
}

/** Stable hash of everything that determines a recommendation. */
export function hashInputs(input: RecommendInput): string {
  const { hole, ...rest } = input;
  return fnv1a(
    stableStringify({
      ...rest,
      hole: hole.geometry,
      samples: input.samples ?? DEFAULT_SAMPLES,
      seed: input.seed ?? DEFAULT_SEED,
      engine: engineVersions(input),
    }),
  );
}
