// GENERATED by `pnpm vendor:engine` from packages/engine/src — do not edit.
/**
 * Rendering geometry in the club frame (§8.7): metres, origin at the ball,
 * +along up the intended line, +lateral to the player's right. Callers map
 * the points to lat/lng with `fromClubFrame`. Polygons are closed (the first
 * point is repeated at the end), GeoJSON-style.
 */
import type { FrameResult } from '../types/index.ts';
import type { ClubPattern, DispersionLevel } from './types.ts';

/**
 * σ multiplier per contour level. For a bivariate normal the radius
 * enclosing probability p is √(−2 ln(1 − p)): 1.794 at 80 %, 2.448 at 95 %.
 */
export const LEVEL_SIGMA_SCALE: Readonly<Record<DispersionLevel, number>> = {
  1: 1,
  0.8: 1.794,
  0.95: 2.448,
};

/** Two-piece lateral scale: `sd_left` for z < 0, `sd_right` otherwise. */
export const lateralScale = (p: ClubPattern, z: number): number =>
  z < 0 ? p.lateral.sd_left : p.lateral.sd_right;

export interface ConeOptions {
  /** Contour level; `1` draws the 1σ core. Default 0.8. */
  quantile?: DispersionLevel;
  /** Segments per arc. Default 24. */
  steps?: number;
}

/**
 * The cone: an annular sector from the ball (radius = shot distance). Its
 * radial extent is mean ± k·sd of distance (near edge clamped at the ball) and its edges are
 * the rays through the lateral bounds at the mean distance —
 * `mean − k·sd_left` and `mean + k·sd_right` — so the sector is skewed by
 * the bias and is wider on the big-miss side. Points run along the far arc
 * left→right, then back along the near arc right→left, then close.
 */
export function conePolygon(pattern: ClubPattern, opts: ConeOptions = {}): FrameResult[] {
  const k = LEVEL_SIGMA_SCALE[opts.quantile ?? 0.8];
  const steps = Math.max(1, Math.round(opts.steps ?? 24));
  const { mean: d, sd } = pattern.distance;
  const thetaL = Math.atan2(pattern.lateral.mean - k * pattern.lateral.sd_left, d);
  const thetaR = Math.atan2(pattern.lateral.mean + k * pattern.lateral.sd_right, d);
  const far = d + k * sd;
  const near = Math.max(0, d - k * sd);
  const pts: FrameResult[] = [];
  for (let i = 0; i <= steps; i++) {
    const th = thetaL + ((thetaR - thetaL) * i) / steps;
    pts.push({ alongM: far * Math.cos(th), lateralM: far * Math.sin(th) });
  }
  for (let i = steps; i >= 0; i--) {
    const th = thetaL + ((thetaR - thetaL) * i) / steps;
    pts.push({ alongM: near * Math.cos(th), lateralM: near * Math.sin(th) });
  }
  pts.push({ ...pts[0]! });
  return pts;
}

/**
 * Map standard-normal coordinates (u, v) to the club frame, honouring rho
 * and the two-piece lateral: along = μd + σd·u, zl = ρu + √(1−ρ²)v,
 * lateral = μl + zl·(zl < 0 ? sd_left : sd_right). Shared by the ellipse and
 * the sampler so the drawn contours match the simulated shots.
 */
export function fromStandardNormal(p: ClubPattern, u: number, v: number): FrameResult {
  const zl = p.rho * u + Math.sqrt(Math.max(0, 1 - p.rho * p.rho)) * v;
  return {
    alongM: p.distance.mean + p.distance.sd * u,
    lateralM: p.lateral.mean + zl * lateralScale(p, zl),
  };
}

/**
 * Contour of the pattern at `level` around its mean: the image of the circle
 * of radius k under {@link fromStandardNormal}. With equal half-SDs this is
 * the usual correlated-normal ellipse; otherwise the left half uses
 * `sd_left` and the right half `sd_right`. The circle is sampled at `steps`
 * even angles plus the two angles where the lateral switches side, so every
 * edge lies within one linear piece and the polygon always encloses the
 * mean. Returns `steps + 2` points plus closure.
 */
export function ellipsePolygon(
  pattern: ClubPattern,
  level: DispersionLevel = 0.8,
  steps = 48,
): FrameResult[] {
  const k = LEVEL_SIGMA_SCALE[level];
  const n = Math.max(3, Math.round(steps));
  const TAU = 2 * Math.PI;
  const s = Math.sqrt(Math.max(0, 1 - pattern.rho * pattern.rho));
  // zl = ρ·cos t + s·sin t vanishes at t0 and t0 + π.
  const t0 = Math.atan2(-pattern.rho, s);
  const ts = Array.from({ length: n }, (_, i) => (TAU * i) / n);
  for (const t of [t0, t0 + Math.PI]) ts.push(((t % TAU) + TAU) % TAU);
  ts.sort((a, b) => a - b);
  const pts = ts.map((t) => fromStandardNormal(pattern, k * Math.cos(t), k * Math.sin(t)));
  pts.push({ ...pts[0]! });
  return pts;
}
