// GENERATED by `pnpm vendor:engine` from packages/engine/src — do not edit.
/**
 * Unit conversions. The engine works in SI (metres, m/s, °C, hPa, radians where
 * noted); anything user-facing converts at the edge with these helpers.
 */

export const METRES_PER_YARD = 0.9144;
export const METRES_PER_FOOT = 0.3048;
export const METRES_PER_SECOND_PER_MPH = 0.44704;
export const METRES_PER_SECOND_PER_KNOT = 0.514444;

export const yardsToMetres = (yd: number): number => yd * METRES_PER_YARD;
export const metresToYards = (m: number): number => m / METRES_PER_YARD;
export const feetToMetres = (ft: number): number => ft * METRES_PER_FOOT;
export const metresToFeet = (m: number): number => m / METRES_PER_FOOT;
export const mphToMps = (mph: number): number => mph * METRES_PER_SECOND_PER_MPH;
export const mpsToMph = (mps: number): number => mps / METRES_PER_SECOND_PER_MPH;
export const knotsToMps = (kt: number): number => kt * METRES_PER_SECOND_PER_KNOT;

export const degToRad = (deg: number): number => (deg * Math.PI) / 180;
export const radToDeg = (rad: number): number => (rad * 180) / Math.PI;

/** Normalise a bearing to [0, 360). */
export const normaliseBearing = (deg: number): number => {
  const r = deg % 360;
  const n = r < 0 ? r + 360 : r;
  // A tiny negative input can round `r + 360` to exactly 360.
  return n >= 360 ? 0 : n;
};

/** Signed smallest difference `b − a` in degrees, in (−180, 180]. */
export const bearingDelta = (a: number, b: number): number => {
  const d = normaliseBearing(b - a);
  return d > 180 ? d - 360 : d;
};
