/**
 * Vendoring of `packages/engine/src` into `supabase/functions/_shared/engine`.
 * Edge Functions are bundled from supabase/functions only, so they cannot
 * import the workspace package; the copy is committed so deploys are
 * reproducible. The only transformation is Deno-compatible import specifiers
 * (`./x.js` → `./x.ts`); test files are left out. Runs under Node
 * (`pnpm vendor:engine`) and Deno (`vendor_test.ts`), hence `node:` imports.
 */
import { readdirSync, readFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

export const ENGINE_SRC = ['packages', 'engine', 'src'];
export const VENDOR_DIR = ['supabase', 'functions', '_shared', 'engine'];

/** Header prepended to every vendored file. */
export const VENDOR_HEADER =
  '// GENERATED by `pnpm vendor:engine` from packages/engine/src — do not edit.\n';

const isSource = (name: string) => name.endsWith('.ts') && !name.endsWith('.test.ts');

/** Relative paths (posix separators) of the engine's non-test sources, sorted. */
export function listSources(srcDir: string): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.isFile() && isSource(e.name)) out.push(relative(srcDir, p).split(sep).join('/'));
    }
  };
  walk(srcDir);
  return out.sort();
}

/** Rewrite relative `.js` specifiers (static and dynamic imports/exports) to `.ts`. */
export function transformSource(source: string): string {
  return (
    VENDOR_HEADER +
    source.replace(
      /(\bfrom\s+|\bimport\s*\(\s*|\bimport\s+)(['"])(\.{1,2}\/[^'"]*?)\.js\2/g,
      '$1$2$3.ts$2',
    )
  );
}

/** Expected vendored files: relative path → content. */
export function expectedVendor(repoRoot: string): Map<string, string> {
  const src = join(repoRoot, ...ENGINE_SRC);
  return new Map(
    listSources(src).map((rel) => [rel, transformSource(readFileSync(join(src, rel), 'utf8'))]),
  );
}

/** Relative paths of every file currently in the vendored directory, sorted. */
export function listVendored(repoRoot: string): string[] {
  const dir = join(repoRoot, ...VENDOR_DIR);
  const out: string[] = [];
  const walk = (d: string) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) walk(p);
      else out.push(relative(dir, p).split(sep).join('/'));
    }
  };
  walk(dir);
  return out.sort();
}
