// GENERATED by `pnpm vendor:engine` from packages/engine/src — do not edit.
/**
 * Geodesy helpers. Shots are at most a few hundred metres, so a local
 * equirectangular projection centred on the start point is accurate to
 * centimetres — that is what the club-frame functions use. Haversine is
 * used for absolute distances (to the pin, to a hazard edge).
 */
import { degToRad, normaliseBearing, radToDeg } from '../units/index.ts';
import type { FrameResult } from '../types/index.ts';

/** WGS-84 mean earth radius, metres. */
export const EARTH_RADIUS_M = 6371008.8;

export interface LatLng {
  lat: number;
  lng: number;
}

/** A planar point in metres relative to some origin: +x east, +y north. */
export interface XY {
  x: number;
  y: number;
}

/** Great-circle distance in metres. */
export function haversineDistanceM(a: LatLng, b: LatLng): number {
  const φ1 = degToRad(a.lat);
  const φ2 = degToRad(b.lat);
  const dφ = φ2 - φ1;
  const dλ = degToRad(b.lng - a.lng);
  const h = Math.sin(dφ / 2) ** 2 + Math.cos(φ1) * Math.cos(φ2) * Math.sin(dλ / 2) ** 2;
  return 2 * EARTH_RADIUS_M * Math.asin(Math.min(1, Math.sqrt(h)));
}

/** Initial bearing from `a` to `b`, degrees true in [0, 360). */
export function initialBearingDeg(a: LatLng, b: LatLng): number {
  const φ1 = degToRad(a.lat);
  const φ2 = degToRad(b.lat);
  const dλ = degToRad(b.lng - a.lng);
  const y = Math.sin(dλ) * Math.cos(φ2);
  const x = Math.cos(φ1) * Math.sin(φ2) - Math.sin(φ1) * Math.cos(φ2) * Math.cos(dλ);
  return normaliseBearing(radToDeg(Math.atan2(y, x)));
}

/** Point reached by travelling `distanceM` from `origin` on `bearingDeg`. */
export function destinationPoint(origin: LatLng, bearingDeg: number, distanceM: number): LatLng {
  const δ = distanceM / EARTH_RADIUS_M;
  const θ = degToRad(bearingDeg);
  const φ1 = degToRad(origin.lat);
  const λ1 = degToRad(origin.lng);
  const sinφ2 = Math.sin(φ1) * Math.cos(δ) + Math.cos(φ1) * Math.sin(δ) * Math.cos(θ);
  const φ2 = Math.asin(sinφ2);
  const y = Math.sin(θ) * Math.sin(δ) * Math.cos(φ1);
  const x = Math.cos(δ) - Math.sin(φ1) * sinφ2;
  const λ2 = λ1 + Math.atan2(y, x);
  return { lat: radToDeg(φ2), lng: radToDeg(λ2) };
}

/**
 * Local equirectangular projection. Returns metres east/north of `origin`.
 * Accurate to ~1 cm within 1 km at Irish latitudes.
 */
export function toLocalXY(origin: LatLng, p: LatLng): XY {
  const k = Math.cos(degToRad(origin.lat));
  return {
    x: degToRad(p.lng - origin.lng) * k * EARTH_RADIUS_M,
    y: degToRad(p.lat - origin.lat) * EARTH_RADIUS_M,
  };
}

/** Inverse of {@link toLocalXY}. */
export function fromLocalXY(origin: LatLng, xy: XY): LatLng {
  const k = Math.cos(degToRad(origin.lat));
  return {
    lat: origin.lat + radToDeg(xy.y / EARTH_RADIUS_M),
    lng: origin.lng + radToDeg(xy.x / (k * EARTH_RADIUS_M)),
  };
}

/**
 * Express `end` in the club frame whose origin is `start` and whose +along
 * axis points on `lineBearingDeg`. +lateral is to the right when facing
 * along the line.
 */
export function toClubFrame(start: LatLng, lineBearingDeg: number, end: LatLng): FrameResult {
  const { x, y } = toLocalXY(start, end);
  const θ = degToRad(lineBearingDeg);
  // Unit vectors: along = (sinθ, cosθ) in (east, north); right = (cosθ, −sinθ).
  return {
    alongM: x * Math.sin(θ) + y * Math.cos(θ),
    lateralM: x * Math.cos(θ) - y * Math.sin(θ),
  };
}

/** Inverse of {@link toClubFrame}. */
export function fromClubFrame(start: LatLng, lineBearingDeg: number, r: FrameResult): LatLng {
  const θ = degToRad(lineBearingDeg);
  return fromLocalXY(start, {
    x: r.alongM * Math.sin(θ) + r.lateralM * Math.cos(θ),
    y: r.alongM * Math.cos(θ) - r.lateralM * Math.sin(θ),
  });
}

/** Axis-aligned bounding box of a ring. */
export interface Bbox {
  minLat: number;
  minLng: number;
  maxLat: number;
  maxLng: number;
}

export function bboxOf(ring: readonly LatLng[]): Bbox {
  let minLat = Infinity;
  let minLng = Infinity;
  let maxLat = -Infinity;
  let maxLng = -Infinity;
  for (const p of ring) {
    if (p.lat < minLat) minLat = p.lat;
    if (p.lat > maxLat) maxLat = p.lat;
    if (p.lng < minLng) minLng = p.lng;
    if (p.lng > maxLng) maxLng = p.lng;
  }
  return { minLat, minLng, maxLat, maxLng };
}

export function bboxContains(b: Bbox, p: LatLng): boolean {
  return p.lat >= b.minLat && p.lat <= b.maxLat && p.lng >= b.minLng && p.lng <= b.maxLng;
}

/**
 * A polygon as an outer ring plus optional holes. Rings need not be closed
 * (a repeated first vertex is tolerated).
 */
export interface Polygon {
  outer: readonly LatLng[];
  holes?: readonly (readonly LatLng[])[];
}

/** Ray-casting point-in-ring test on lat/lng treated as planar (fine at course scale). */
export function pointInRing(ring: readonly LatLng[], p: LatLng): boolean {
  let inside = false;
  const n = ring.length;
  for (let i = 0, j = n - 1; i < n; j = i++) {
    const a = ring[i]!;
    const b = ring[j]!;
    const crosses = a.lat > p.lat !== b.lat > p.lat;
    if (crosses) {
      const lngAtP = ((b.lng - a.lng) * (p.lat - a.lat)) / (b.lat - a.lat) + a.lng;
      if (p.lng < lngAtP) inside = !inside;
    }
  }
  return inside;
}

export function pointInPolygon(poly: Polygon, p: LatLng): boolean {
  if (!pointInRing(poly.outer, p)) return false;
  for (const hole of poly.holes ?? []) {
    if (pointInRing(hole, p)) return false;
  }
  return true;
}

/** Shortest distance in metres from `p` to the segment `a`–`b`, computed in the local plane around `p`. */
export function distanceToSegmentM(p: LatLng, a: LatLng, b: LatLng): number {
  const A = toLocalXY(p, a);
  const B = toLocalXY(p, b);
  const dx = B.x - A.x;
  const dy = B.y - A.y;
  const len2 = dx * dx + dy * dy;
  // Parameter of the projection of the origin (p) onto AB, clamped to the segment.
  const t = len2 === 0 ? 0 : Math.max(0, Math.min(1, -(A.x * dx + A.y * dy) / len2));
  const cx = A.x + t * dx;
  const cy = A.y + t * dy;
  return Math.hypot(cx, cy);
}

/** Distance from `p` to the nearest edge of the ring, metres (0 if `p` is a vertex). */
export function distanceToRingM(ring: readonly LatLng[], p: LatLng): number {
  let best = Infinity;
  const n = ring.length;
  for (let i = 0, j = n - 1; i < n; j = i++) {
    const d = distanceToSegmentM(p, ring[j]!, ring[i]!);
    if (d < best) best = d;
  }
  return best;
}

/** Planar centroid of a ring (area-weighted). Falls back to the vertex mean for degenerate rings. */
export function ringCentroid(ring: readonly LatLng[]): LatLng {
  const origin = ring[0]!;
  const pts = ring.map((p) => toLocalXY(origin, p));
  let area = 0;
  let cx = 0;
  let cy = 0;
  const n = pts.length;
  for (let i = 0, j = n - 1; i < n; j = i++) {
    const a = pts[j]!;
    const b = pts[i]!;
    const cross = a.x * b.y - b.x * a.y;
    area += cross;
    cx += (a.x + b.x) * cross;
    cy += (a.y + b.y) * cross;
  }
  if (Math.abs(area) < 1e-9) {
    const mean = pts.reduce((s, p) => ({ x: s.x + p.x / n, y: s.y + p.y / n }), { x: 0, y: 0 });
    return fromLocalXY(origin, mean);
  }
  area *= 0.5;
  return fromLocalXY(origin, { x: cx / (6 * area), y: cy / (6 * area) });
}
